#!/bin/bash
base_dir=$(cd "$(dirname "$0")"; pwd)

## install guke
${base_dir}/software-install/install-guake

## install markdown
${base_dir}/software-install/install-markdown

## install emacs
${base_dir}/software-install/install-emacs24
${base_dir}/settings/emacs-setting/init-with-purcell-setting

## install node
${base_dir}/software-install/install-nodejs
${base_dir}/npm-install/install-yo-bower-grunt

## install ruby and compass
${base_dir}/software-install/install-ruby-and-compass


## install shutter
${base_dir}/software-install/install-shutter

## install mongoDB
#${base_dir}/software-install/install-mongodb

## install zsh
${base_dir}/software-install/install-zsh

# install ack
${base_dir}/software-install/install-ack

# install htop
${base_dir}/software-install/install-htop
