#!/bin/bash
# https://github.com/LuRsT/hr
cd source-install
git clone git@github.com:LuRsT/hr.git
cd hr
# Open Makefile and edit the PREFIX variable, specifying the directory where you'd want the software to reside. Then:
sudo make install
