#!/bin/bash
# http://gnomepomodoro.org/
# a pomodo timer
curl -L http://download.opensuse.org/repositories/home:kamilprusko/xUbuntu_14.04/Release.key | sudo apt-key add -
sudo apt-add-repository http://download.opensuse.org/repositories/home:kamilprusko/xUbuntu_14.04/
sudo apt-get update
sudo apt-get install gnome-pomodoro
