#!/bin/bash
# https://github.com/VitaliyRodnenko/geeknote
# Install dependencies. (This example for Debian-based systems):
#$ [sudo] apt-get update; [sudo] apt-get -y install python-setuptools

# Download the repository.
git clone git://github.com/VitaliyRodnenko/geeknote.git

cd geeknote

# Installation
sudo python setup.py install

# Launch Geeknote and go through login procedure.
geeknote login
