#!/bin/bash
# all search should support fuzzy match
# so in github there two command support it. the fzf and the selecta
# so the fzf is more suit.
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
