#!/bin/bash
sudo apt-get install -y -q  ibus ibus-clutter ibus-gtk ibus-gtk3 ibus-qt4
im-switch -s ibus

# sudo apt-get install -y -q  ibus-pinyin
# sudo apt-get install -y -q  ibus-table-wubi
sudo apt-get install -y -q  ibus-googlepinyin
# sudo apt-get install -y -q  ibus-sunpinyin

ibus-setup
# ibus-daemon -drx
