#!/bin/bash
# https://github.com/glenbot/dotjs-ubuntu
# Install
#
# git clone https://github.com/glenbot/dotjs-ubuntu.git
# cd dotjs-ubuntu
# rake install
# After installation add the following line to your crontab
#
# $ crontab -e
# @reboot /path/to/home/bin/djsd -d
# For the impatient run the daemon right away
#
# djsd -d
# For the patient reboot and enjoy!
#
# Now open https://localhost:3131 in Chrome and enable the SSL.
#
# Then install the Google Chrome extension:
#
# http://bit.ly/dotjs