#!/bin/bash
# website : http://beyondgrep.com
#if use apt-get to install ack ,you should use ack-grep.
#sudo apt-get install -y -q  ack-grep
curl http://beyondgrep.com/ack-2.14-single-file > ~/bin/ack && chmod 0755 ~/bin/ack
