#!/bin/bash
# https://webpack.github.io
# The main purpose is to bundle JavaScript files for usage in a browser, yet it is also capable of transforming, bundling, or packaging just about any resource or asset.
sudo npm install -g webpack