#!/bin/bash
# https://github.com/dbcli/pgcli
# Postgres CLI with autocompletion and syntax highlighting
sudo apt-get install -y -q python-pip
sudo apt-get install -y -q python-dev
sudo pip install pgcli
