#!/bin/bash
#: Title                  : install-lein
#: Synopsis               : none
#: Date                   :
#: Author                 : shulei
#: version                : 1.0
#: Description            : install lein
#: Options                : -v set to display message

pushd $PWD

## Script path
script_path="${0%/*}"  # remove the script name ,get the path
script_path=${script_path/\./$(pwd)} # if path start with . , replace with $PWD
cd "${script_path}"

## source lib
source ../libbash/bashr.sh

##init parameters
MESSAGE_ENABLED=n


## get parameters
## parse command-line options,  -m
while getopts "vb:" var
do
    case $var in
        v)
            MESSAGE_ENABLED=y
            ;;
    esac
done
shift $(( $OPTIND - 1 ))

##content
echoH1 "Start install lein"

setup "cp lein to ~/bin" \
    cp -f lein ~/bin/lein \
    "cp lein to ~/bin failed" \
    ;

popd > /dev/null
