#!/bin/bash
sudo apt-get install -y -q g++ python-dev python-numpy \
libgtk-3-dev python-gi-dev gir1.2-gtk-3.0 python-gi-cairo \
swig scons gettext libpng12-dev liblcms2-dev libjson0-dev
git clone https://github.com/mypaint/mypaint.git ~/source-install/mypaint
cd ~/source-install/mypaint
scons
