#!/bin/bash -e
# https://github.com/rvm/rvm

command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -L https://get.rvm.io | bash -s stable --autolibs=enabled --ruby
# curl -L https://get.rvm.io | bash -s stable --autolibs=enabled --ruby --rails --trace

sed -i -e 's/ftp\.ruby-lang\.org\/pub\/ruby/ruby\.taobao\.org\/mirrors\/ruby/g' ~/.rvm/config/db

gem sources --remove https://rubygems.org/
gem sources -a https://ruby.taobao.org/
gem sources -l

gem install bundler
bundle config mirror.https://rubygems.org https://ruby.taobao.org
